/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StakingStakeStakeIdRouteImport } from './routes/staking.stake.$stakeId'

const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingStakeStakeIdRoute = StakingStakeStakeIdRouteImport.update({
  id: '/stake/$stakeId',
  path: '/stake/$stakeId',
  getParentRoute: () => StakingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRouteWithChildren
  '/staking/stake/$stakeId': typeof StakingStakeStakeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRouteWithChildren
  '/staking/stake/$stakeId': typeof StakingStakeStakeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRouteWithChildren
  '/staking/stake/$stakeId': typeof StakingStakeStakeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/staking' | '/staking/stake/$stakeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/staking' | '/staking/stake/$stakeId'
  id: '__root__' | '/' | '/sitemap.xml' | '/staking' | '/staking/stake/$stakeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StakingRoute: typeof StakingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking/stake/$stakeId': {
      id: '/staking/stake/$stakeId'
      path: '/stake/$stakeId'
      fullPath: '/staking/stake/$stakeId'
      preLoaderRoute: typeof StakingStakeStakeIdRouteImport
      parentRoute: typeof StakingRoute
    }
  }
}

interface StakingRouteChildren {
  StakingStakeStakeIdRoute: typeof StakingStakeStakeIdRoute
}

const StakingRouteChildren: StakingRouteChildren = {
  StakingStakeStakeIdRoute: StakingStakeStakeIdRoute,
}

const StakingRouteWithChildren =
  StakingRoute._addFileChildren(StakingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StakingRoute: StakingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
